### ISSUE TITLE
作者您好。关于你开源的代码的一些问题

### ISSUE THREAD

**Issue by nwpuhq** [sczhou/DAVANet#11]
您好，在原论文中，DeblurNet第13-14的子块是AtrousResBlock，但是在开源的代码中使用的ResBlock，是不是开源时代码不小心错误？
如果黄色子块确实是AtrousResBlock而不是ResBlock，可以给出AtrousResBlock的结果吗？因为您在论文中没有描述AtrousResBlock的结构
如果能够解答，真心感谢！

**Comment by sczhou** [comment]
Hi你好，

AtrousResBlock就是增加了dialation，我们代码没有给错（见下图），你再自己check一下哈~
[image: image.png]

祝好，
Shangchen

**Comment by sczhou** [comment]
另外我们在supp文件里给了具体的模型结构，
https://shangchenzhou.com/assets/paper/DAVANet-supp.pdf
可以参考

Shangchen
