### ISSUE TITLE
ZED camera calibration

### ISSUE THREAD

**Issue by oaishi** [sczhou/DAVANet#12]
Hello, thank you so much for the great repository. I wanted to know about the procedure of your dataset preparation. Did you use the default calibration settings of ZED camera? Or redefined the calibration yourself?

**Comment by sczhou** [comment]
Hi, we obtained these images using default calibration settings of the ZED camera. Specifically, we processed the captured videos using the official API of the ZED camera. More information (examples, tutorials, and API) can be found from this [link](https://github.com/stereolabs).

**Comment by oaishi** [comment]
Thank you so much for your helpful reply!

**Comment by oaishi** [comment]
Dear Shangchen Zhou,

Thank you so much for the helpful information. I looked over the examples provided in the official guidelines by ZED SDK. Specifically, I followed this tutorial [(https://www.stereolabs.com/docs/video/camera-calibration/#)](https://www.stereolabs.com/docs/video/camera-calibration/#) to obtain the default CalibrationParameters of Zed camera. Unfortunately, I was unable to obtain the values as I could not run it for not having any ZED camera available with me. 

Can you please help me to obtain the [Calibration Parameters](https://www.stereolabs.com/docs/api/structsl_1_1CalibrationParameters.html) ( specifically calibration_params.left_cam, calibration_params.right_cam and calibration_params.stereo_transform ) ? I shall be really grateful to you.

**Comment by sczhou** [comment]
Hi,

You can find the calibration file of the ZED camera from here (https://support.stereolabs.com/hc/en-us/articles/360007497173-What-is-the-calibration-file-). You can also contact ZED to get the calibration file, our dataset was captured by ZED v1 version.

Note that the image pairs in our dataset have been calibrated alright.

**Comment by oaishi** [comment]
Thank you so much for your helpful reply! I have been able to locate the calibration file.
