### ISSUE TITLE
The pretrained model

### ISSUE THREAD

**Issue by yazeedhasan97** [sczhou/DAVANet#14]
Hi DAVANet Team,

Can you please share the pre-trained model so we can test on it

**Comment by sczhou** [comment]
Hi,

Please check out our pre-trained model [here](https://hiteducn0-my.sharepoint.com/:f:/g/personal/sczhou_hit_edu_cn/EqhdLrwXbStCiQl00Em1ak8B-8TL63t1_gMooImX80zfxA).
