### ISSUE TITLE
some  questions about the test result

### ISSUE THREAD

**Issue by gittigxuy** [sczhou/DAVANet#2]
when I set the phase to test,I get the following result,I could not find the deblur result,and the deblured picture's color strange,what should I do?
![result](https://user-images.githubusercontent.com/15090557/57935414-54b4d000-78f4-11e9-93e5-8947ef714098.jpg)

left picture is original picture,the middle picture is original sharp picture,and the right picture is deblured picture use your given model{ckpt-best.pth.zip}

**Comment by sczhou** [comment]
I'm sorry about that, I guess that's my problem, and I will solve it as soon as possible.
Thanks!

**Comment by gittigxuy** [comment]
furthermore,I change your code to train gopro dataset use your given pretrained model{ckpt-best.pth.zip} and use  your deblurnet part,the train speed is too slow and it does not have deblur effect.I am looking forward you to update your code.Thanks

**Comment by sczhou** [comment]
I fixed this bug, and you need to download the pre-trained model again.
Thanks!

**Comment by gittigxuy** [comment]
Thanks,could you share  your  demo result and the original blur image?I will try your new code next Monday.
