### ISSUE TITLE
one question about build.py

### ISSUE THREAD

**Issue by ChuShouTianYuan** [sczhou/DAVANet#5]
in build.py line124

deblurnet_lr_scheduler = torch.optim.lr_scheduler.MultiStepLR(dispnet_solver,milestones=cfg.TRAIN.DEBLURNET_LR_MILESTONES,gamma=cfg.TRAIN.LEARNING_RATE_DECAY)

why 'dispnet_solver' appears here....
thanks for much

**Comment by sczhou** [comment]
Thanks for pointing out this bug, the released version had some modifications. Sorry about that.
I had fixed it.
