### ISSUE TITLE
Trying to run inference using deblurnet on GOPRO dataset

### ISSUE THREAD

**Issue by TouqeerAhmad** [sczhou/DAVANet#6]
Hello, I am trying to run the inference using the deblurnet module of DAVANet. Have changed the flags appropriately in the config file. But, when it goes to build_net(cfg) -- it gives me the following error:

"size mismatch for module.upconv3_i.0.weight: copying a param with shape torch.Size([128, 288, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 128, 3, 3])."

It is somehow complaining about the mismatch in the tensor sizes but I am not sure why this could be. Please advise!

**Comment by sczhou** [comment]
The param of DeblurNet used for single and stereo are different. The following Table (Configurations of DeblurNet) may help you.
![image](https://user-images.githubusercontent.com/14334509/61098372-52ed3000-a491-11e9-92ff-ff0a6a5da820.png)

**Comment by TouqeerAhmad** [comment]
But I am specifying 'DeblurNet' instead of 'StereoDeblurNet' in the configuration file, and still the network complains about the tensor size mismatch. As from your Table1, it feels you have two different models for deblurring; one using the fuse information from fusionNet and DispBiNet while other not using this information. Is the trained model doing mono deblurring available?
