### ISSUE TITLE
Trying to run inference using deblurnet on GOPRO dataset -- again

### ISSUE THREAD

**Issue by TouqeerAhmad** [sczhou/DAVANet#7]
Hi I am following up the question I asked earlier in here:

https://github.com/sczhou/DAVANet/issues/6

But I am specifying 'DeblurNet' instead of 'StereoDeblurNet' in the configuration file, and still the network complains about the tensor size mismatch. As from your Table1, it feels you have two different models for deblurring; one using the fuse information from fusionNet and DispBiNet while other not using this information. Is the trained model doing mono deblurring available?

Also, can you please not close an issue as someone could have follow up questions.

**Comment by sczhou** [comment]
you need to change the channel number (from 288 to 128) in DeblurNet, according to the configuration [Table](https://user-images.githubusercontent.com/14334509/61098372-52ed3000-a491-11e9-92ff-ff0a6a5da820.png).

**Comment by zrongcheng** [comment]
I have the same question, I also want to train model with single image. @sczhou
